# One line per downstream pipeline: <watched-path>:<buildkite-pipeline-slug>
# service-a:deploy below means we are watching the service-a folder and will trigger a Buildkite pipeline named deploy
services/service-a:deploy
services/service-b:pull-request
