# One line per downstream pipeline: <watched-path>:<buildkite-pipeline-slug>
# service-b:deploy below means we are watching the service-b folder and will trigger a Buildkite pipeline named deploy
services/service-b:deploy
